baseurl = "https://jcarpent.github.io/"
title = ""
copyright = "&copy; 2017 Justin Carpentier"
languageCode = "en-us"
theme = "academic"

# Enable comments by entering your Disqus shortname
disqusShortname = ""

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-84493145-1"

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false


[params]
  name = "Justin Carpentier"
  role = "PhD candidate"
  organization = "LAAS-CNRS"
  avatar = "portrait.jpg"
  email = "justin.carpentier_AT_laas.fr"
  address = "7 avenue du Colonel Roche, 31077 Toulouse Cedex 4, France."
  phone = "+33 5.61.33.68.30"

  # Enable Keybase in Contact section by entering your keybase.io username.
  keybase = ""

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Mon, Jan 2, 2006"

  # Enable global LaTeX math rendering? If false, you can enable it locally on a per page basis.
  math = true

  # Enable native social sharing buttons?
  sharing = true

  # Link custom CSS and JS assets (relative to /static/css and /static/js respectively)
  custom_css = []
  custom_js  = []

  # Publication types.
  #   Used to categorize publications.
  #   The index of the publication type in the list is used as its unique numerical identifier.
  #   The numeric ID is used in a publication's frontmatter to categorize it. 
  #   The language can be edited below.
  #   For multi-lingual sites, copy this block to each language section at the end of this file.
  publication_types = [ 
    'Uncategorized',  # 0 
    'Conference proceedings',  # 1 
    'Journal',  # 2 
    'Workshop proceedings',  # 3 
    'Work in progress',  # 4
    'Technical report',  # 5 
    'Book',  # 6 
    'Book chapter'  # 7 
  ]

  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus, youtube, instagram, soundcloud
  #   For email icon, use "fa" icon pack, "envelope" icon, and "mailto:your@email.com" as the link.
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:jcarpent@laas.fr"

  [[params.social]]
    icon = "phone"
    icon_pack = "fa"
    link = "tel:+33.5.61.33.68.30"

  [[params.social]]
    icon = "google-scholar"
    icon_pack = "ai"
    link = "https://scholar.google.com/citations?user=CyhIdmMAAAAJ"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "https://github.com/jcarpent"

  [[params.social]]
    icon = "researchgate"
    icon_pack = "ai"
    link = "https://www.researchgate.net/profile/Justin_Carpentier"

# Navigation Links
#   The weight parameter defines the order that the links will appear in. 

[[menu.main]]
  name = "Home"
  url = "#top"
  weight = 1 

[[menu.main]]
  name = "Publications"
  identifier = "Publication_menu"
#  url = "publication/"
  weight = 2 

[[menu.main]]
  name = "Submissions"
  parent = "Publication_menu"
  url = "#submissions"
  weight = 3

[[menu.main]]
  name = "Selected publications"
  parent = "Publication_menu"
  url = "#publications_selected"
  weight = 4

[[menu.main]]
  name = "Recent publications"
  parent = "Publication_menu"
  url = "#publications"
  weight = 5

[[menu.main]]
  name = "All publications"
  parent = "Publication_menu"
  url = "publication/"
  weight = 6 

#[[menu.main]]
#  name = "Posts"
#  url = "#posts"
#  weight = 3 
#
#[[menu.main]]
#  name = "Projects"
#  url = "#projects"
#  weight = 4 
#
#[[menu.main]]
#  name = "Teaching"
#  url = "#teaching"
#  weight = 5 
#
#[[menu.main]]
#  name = "Contact"
#  url = "#contact"
#  weight = 6 

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"

# Languages
#   Create a [languages.X] block for each language you want, where X is the language ID. 

# Configure the English version of the website.
[languages.en]
  languageCode = "en-us"
